language: python 
python: 
  - "3.5"
cache: pip
services: 
  - sqlite3
env: 
  - DJANGO=2.2.4 DB=sqlite3
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: test
      script: 
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test
    - stage: stage
      script:
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test

