language: python 
python: 
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
services: 
  - sqlite3
env: 
  - DJANGO=2.2.4 DB=sqlite3
install:
  - pip install -r requirements.txt
script: 
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - python manage.py behave
