# Generated by Django 2.2.3 on 2019-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_carnet', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=15)),
                ('student_grade', models.IntegerField()),
                ('student_semester', models.IntegerField()),
            ],
        ),
    ]
