# Generated by Django 2.2.3 on 2019-08-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0005_auto_20190813_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadepartamento',
            name='coordinacion',
        ),
    ]
