# Generated by Django 2.2.3 on 2019-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0006_remove_listadepartamento_coordinacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='departamento',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
