# Generated by Django 2.2.3 on 2019-08-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0002_circle_departamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Coordinacion',
        ),
    ]
