# Generated by Django 2.2.4 on 2019-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0002_auto_20191015_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='ingreso',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='listadepartamento',
            name='ingreso',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ingreso',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
