# Generated by Django 2.2.3 on 2019-08-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0003_auto_20190813_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinacion',
            new_name='Departamento',
        ),
    ]
