# Generated by Django 2.2.4 on 2019-10-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0003_auto_20191016_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Ingreso circulo',
                'verbose_name_plural': 'Ingresos circulos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('iger.circle',),
        ),
    ]
