# Generated by Django 2.2.3 on 2019-08-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0004_auto_20190813_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDepartamento',
            fields=[
                ('coordinacion', models.IntegerField()),
                ('departamento', models.CharField(max_length=31, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
