# Generated by Django 2.2.4 on 2019-09-14 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0007_auto_20190813_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studen_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iger.Circle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=35),
        ),
    ]
