# Generated by Django 2.2.4 on 2019-09-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0007_auto_20190813_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_carnet',
            new_name='carnet',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_grade',
            new_name='grado',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_semester',
            new_name='semestre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='nombre_completo',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
    ]
