# Generated by Django 2.2.4 on 2019-09-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0008_auto_20190913_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studen_circle',
            new_name='student_circle',
        ),
    ]
