# Generated by Django 2.2.4 on 2019-09-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0008_auto_20190913_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='circle_code',
            new_name='codigo_circulo',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='circle_number',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='id_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='name_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='num_x',
        ),
        migrations.AddField(
            model_name='circle',
            name='coordinacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iger.ListaDepartamento'),
            preserve_default=False,
        ),
    ]
