# Generated by Django 2.2.4 on 2019-09-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0009_auto_20190913_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='circulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iger.Circle'),
        ),
    ]
