# Generated by Django 2.2.4 on 2019-09-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0009_auto_20190913_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_carnet',
            new_name='carnet',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_circle',
            new_name='circulo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_grade',
            new_name='grado',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_semester',
            new_name='semestre',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='circle_code',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='circle_number',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='id_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='name_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='num_x',
        ),
        migrations.AddField(
            model_name='circle',
            name='codigo_circulo',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='coordinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iger.ListaDepartamento'),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='departamento',
            field=models.CharField(max_length=30),
        ),
    ]
