# Generated by Django 2.2.4 on 2019-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0010_student_circulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ingreso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
