# Generated by Django 2.2.4 on 2019-09-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0011_auto_20190913_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='circulo',
        ),
    ]
