# Generated by Django 2.2.4 on 2019-10-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0011_student_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ingreso',
        ),
    ]
