# Generated by Django 2.2.4 on 2019-09-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0012_remove_student_circulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='codigo_circulo',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='coordinacion',
        ),
        migrations.AddField(
            model_name='circle',
            name='circle_code',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='circle_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='id_coor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='name_coor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='num_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='circulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iger.Circle'),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='departamento',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
