# Generated by Django 2.2.4 on 2019-09-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0013_auto_20190913_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='circle_code',
            new_name='codigo_circulo',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='circle_number',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='id_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='name_coor',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='num_x',
        ),
        migrations.AddField(
            model_name='circle',
            name='coordinacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iger.ListaDepartamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='departamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='circulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iger.Circle', to_field='circle_code'),
        ),
    ]
