# Generated by Django 2.2.4 on 2019-09-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0014_auto_20190913_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='coordinacion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='circulo',
        ),
    ]
