# Generated by Django 2.2.4 on 2019-09-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0015_auto_20190913_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='departamento',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
