# Generated by Django 2.2.4 on 2019-09-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iger', '0016_auto_20190913_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='codigo_circulo',
            new_name='circle_code',
        ),
        migrations.AddField(
            model_name='circle',
            name='circle_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='id_coor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='name_coor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='num_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadepartamento',
            name='coordinacion',
            field=models.CharField(max_length=2),
        ),
    ]
